package com.ninjaTurtles.champtheatre.service;

import com.ninjaTurtles.champtheatre.models.Employee;
import com.ninjaTurtles.champtheatre.models.EmployeeAccount;
import com.ninjaTurtles.champtheatre.models.Reservation;

public interface EmailService {
	
	void sendAutoGeneratedPassword(Employee email, EmployeeAccount password);
	
	void sendReserveStatusUpdate(Reservation reservation, Employee email);
	
	void sendPasswordChange(Employee email);

}
