package com.ninjaTurtles.champtheatre.service;

import com.ninjaTurtles.champtheatre.models.Employee;
import com.ninjaTurtles.champtheatre.models.EmployeeAccount;
import com.ninjaTurtles.champtheatre.models.Reservation;

import javax.mail.MessagingException;

public interface EmailSenderService {
    void sendEmail(String to, String subject, String message);

    void sendAutoGeneratedPassword(Employee email, EmployeeAccount password) throws MessagingException;

    void sendReserveStatusUpdate(Reservation reservation, Employee email) throws MessagingException;

    void sendPasswordChange(Employee email) throws MessagingException;
    void sendReservationConfirmation(Reservation reservation, Employee email) throws MessagingException;
}
